version: '3'
services:
    master:
        container_name: master
        build:
            context: ./
            dockerfile: master/Dockerfile
        restart: always
        platform: linux/x86_64
        environment:
            MYSQL_DATABASE: 'hotel_reservation'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: '1234'
            MYSQL_ROOT_PASSWORD: '1234'
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
        ports:
            - '3304:3306'
        volumes:
            - master:/var/lib/mysql
            - master:/var/lib/mysql-files
        networks:
            - net

    slave:
        container_name: slave
        build:
            context: ./
            dockerfile: slave/Dockerfile
        restart: always
        platform: linux/x86_64
        environment:
            MYSQL_DATABASE: 'hotel_reservation'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: '1234'
            MYSQL_ROOT_PASSWORD: '1234'
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
        ports:
            - '3305:3306'
        volumes:
            - slave:/var/lib/mysql
            - slave:/var/lib/mysql-files
        networks:
            - net

volumes:
    master:
    slave:

networks:
    net:
        driver: bridge
